version: "3.9"
services:
  elasticsearch:
    container_name: elastic_search
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"


  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - docker-compose.env
    depends_on:
      - elasticsearch

