version: "3.9"
services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - elasticsearch

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PORT: 3306
    ports:
      - "3302:3306"
    volumes:
      - ./data/mysql/dbb:/var/lib/mysql

  elasticsearch:
    container_name: elastic_search
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

